version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/flight_booking
      - JWT_SECRET=changeme_supersecret
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./exports:/app/exports

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
